name: Release
# on:
#   push:
#     branches:
#       - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Auto-Create Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Print Created Release
        if: ${{ steps.release.outputs.released == 'true' }}
        run: echo Release ID ${{ steps.release.outputs.release_id }}